

import '../../frequent_used_widget/errors_display.dart';

class WidgetCollection{
  List<String> name_of_simple_widget =[
    'AppBar',
    'Sliver AppBar',
    'Material App',
    'Scaffold',
    'Container',
    'Sizebox',
    'Text',
    'Column',
    'Row',
    'Icons',
    'Image',
    'List View',
    'Grid View',
    'Stack',
    'Drawer',
    'Card',
    'Bottom Navigation Bar',
    'Silver Grid',
    'Silver List',
  ];
  List<Function> Screens_of_simple_widget =[
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    () => ErrorDisplay().showUnderConstructionDialog(),
    // 'Sliver AppBar',
    // 'Material App',
    // 'Scaffold',
    // 'Container',
    // 'Sizebox',
    // 'Text',
    // 'Column',
    // 'Row',
    // 'Icons',
    // 'Image',
    // 'List View',
    // 'Grid View',
    // 'Stack',
    // 'Drawer',
    // 'Card',
    // 'Bottom Navigation Bar',
    // 'Silver Grid',
    // 'Silver List',
  ];
}